
CREATE DATABASE BNGRC;
USER BNGRC;

CREATE OR REPLACE TABLE Besoin(
    idBesoin INT PRIMARY KEY AUTO_INCREMENT,
    idTypeBesoin INT,
    valBesoin VARCHAR(100)
);

CREATE OR REPLACE TABLE EquivalenceBesoin(
    idEquivalenceBesoin INT PRIMARY KEY AUTO_INCREMENT,
    idBesoin INT,
    prixUnitaire DOUBLE,
    quantite DOUBLE,
    val VARCHAR(50)
);

CREATE OR REPLACE TABLE TypeBesoin(
    idTypeBesoin INT PRIMARY KEY AUTO_INCREMENT,
    valTypeBesoin VARCHAR(100)
);

CREATE OR REPLACE TABLE Region(
    idRegion INT PRIMARY KEY AUTO_INCREMENT,
    valRegion VARCHAR(100)
);

CREATE OR REPLACE TABLE Ville(
    idVille INT PRIMARY KEY AUTO_INCREMENT,
    idRegion INT,
    valVille VARCHAR(100)
);

CREATE OR REPLACE TABLE Don(
    idDon INT PRIMARY KEY AUTO_INCREMENT,
    dateDon DATE,
    totalPrix DOUBLE
);

