-- Combined SQL: schema (CREATE) then data (INSERT/DELETE/ALTER/UPDATE)
-- Generated by assistant

-- SCHEMA
CREATE DATABASE IF NOT EXISTS BNGRC;
USE BNGRC;

-- Tables from 16_02_2026_01_base.sql
CREATE  TABLE Besoin(
    idBesoin INT PRIMARY KEY AUTO_INCREMENT,
    valBesoin VARCHAR(100),
    idVille INT,
    idType INT
);

CREATE  TABLE Region(
    idRegion INT PRIMARY KEY AUTO_INCREMENT,
    valRegion VARCHAR(100)
);

CREATE  TABLE Ville(
    idVille INT PRIMARY KEY AUTO_INCREMENT,
    idRegion INT,
    valVille VARCHAR(100)
);

CREATE  TABLE Don(
    idDon INT PRIMARY KEY AUTO_INCREMENT,
    dateDon DATE,
    totalPrix DOUBLE
);

CREATE  TABLE Produit(
    idProduit INT PRIMARY KEY AUTO_INCREMENT,
    valProduit VARCHAR(100),
    idType INT
);

CREATE  TABLE EquivalenceProduit(
    idEquivalenceProduit INT PRIMARY KEY AUTO_INCREMENT,
    idProduit INT,
    quantite DOUBLE,
    val VARCHAR(50),
    prix DOUBLE
);

CREATE  TABLE ProduitBesoin(
    idProduitBesoin INT PRIMARY KEY AUTO_INCREMENT,
    idProduit INT,
    idBesoin INT
);

CREATE  TABLE Donnation(
    idDonnation INT PRIMARY KEY AUTO_INCREMENT,
    idDon INT,
    idProduit INT,
    quantiteProduit DECIMAL(10,2)
);

CREATE  TABLE type(
    idType INT PRIMARY KEY AUTO_INCREMENT,
    valType VARCHAR(100)
);

-- View from 16_02_2026_03_view.sql
CREATE  VIEW DonnationEquivalence AS
(SELECT e.idEquivalenceProduit,e.idProduit,d.idDonnation,d.idDon,d.quantiteProduit,e.quantite,e.prix,e.val
FROM Donnation d JOIN
EquivalenceProduit e ON d.idProduit = e.idProduit);

-- Dispatch tables from 16_02_2026_04.sql
CREATE TABLE IF NOT EXISTS Dispatch_mere (
    id_Dispatch_mere INT NOT NULL AUTO_INCREMENT,
    id_ville INT DEFAULT NULL,
    date_dispatch DATETIME NOT NULL,
    PRIMARY KEY (id_Dispatch_mere)
);

CREATE TABLE IF NOT EXISTS Dispatch_fille (
    id_Dispatch_fille INT NOT NULL AUTO_INCREMENT,
    id_Dispatch_mere INT NOT NULL,
    id_produit INT NOT NULL,
    quantite INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id_Dispatch_fille)
);

-- Stockage table
CREATE  TABLE Stockage(
    idStockage INT PRIMARY KEY AUTO_INCREMENT,
    idProduit INT NOT NULL UNIQUE,
    quantite INT
);

-- Equivalence_date table
CREATE  TABLE Equivalence_date (
    idEquivalence INT PRIMARY KEY AUTO_INCREMENT,
    id_besoin INT NOT NULL,
    date_equivalence DATE NOT NULL
);

-- Historique_dispatch and TypeDispatch (may be non-standard CREATE syntax in source)
CREATE TABLE IF NOT EXISTS Historique_dispatch (
    idHistorique INT PRIMARY KEY AUTO_INCREMENT,
    idTypeDispatch INT,
    idVille INT,
    idBesoin INT,
    date_change DATE,
    status VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS TypeDispatch (
    idTypeDispatch INT PRIMARY KEY AUTO_INCREMENT,
    nomType VARCHAR(255)
);

-- New tables: StatutBesoin, Statut
CREATE  TABLE StatutBesoin(
    IdStatutBesoin INT PRIMARY KEY AUTO_INCREMENT,
    ValStatutBesoin VARCHAR(100) NOT NULL
);

CREATE  TABLE Statut(
    IdStatut INT PRIMARY KEY AUTO_INCREMENT,
    IdBesoin INT,
    IdStatutBesoin INT,
    DateDeChangement DATETIME
);

